// Generated by CoffeeScript 1.3.1
(function() {
  var arraydb, assert, author, book, functools, map, mapdb, testCreatingSubDocs, testFind, testGet, testNewDocument, testRemove, testRemoveByQueries, testRemoveSubDocs, testSave, testSaveSubDocs, testToJSON, testValidation;

  assert = require('assert');

  functools = require('functools');

  map = require('../lib');

  book = require('./content/book');

  arraydb = require('./array-db');

  author = require('./content/author');

  mapdb = require('./map-db');

  testNewDocument = function(callback) {
    var doc1, doc2, driver1, schema1;
    driver1 = map({
      find: function() {},
      get: function() {},
      save: function() {},
      id: 'foo'
    });
    schema1 = driver1({
      foo: String,
      bar: String
    });
    doc1 = schema1({
      foo: 'hello-world',
      bar: 'corge-quux'
    });
    doc2 = schema1({
      foo: {
        'a': 1
      },
      bar: 3.14
    });
    assert.equal(doc1.id(), 'hello-world');
    assert.equal(doc1.foo(), 'hello-world');
    assert.equal(doc1.bar(), 'corge-quux');
    assert.equal(doc2.id().a, 1);
    assert.equal(doc2.foo().a, 1);
    assert.equal(doc2.bar(), 3.14);
    assert.equal(doc1.id.isDocument, true);
    assert.equal(doc1.id.schema, schema1);
    return callback();
  };

  testCreatingSubDocs = function(callback) {
    var ontheroad, whitefang;
    whitefang = book({
      index: 0,
      title: 'white fang',
      author: {
        key: 'jl',
        first_name: 'Jack',
        last_name: 'London'
      }
    });
    ontheroad = book({
      index: 1,
      title: 'on the road',
      author: author({
        key: 'jk',
        first_name: 'Jack',
        last_name: 'Kerouac'
      })
    });
    assert.equal(whitefang.id(), 0);
    assert.equal(whitefang.title(), 'White Fang');
    assert.equal(whitefang.author.id(), 'jl');
    assert.equal(whitefang.author.firstName(), 'Jack');
    assert.equal(whitefang.author.lastName(), 'London');
    assert.equal(ontheroad.id(), 1);
    assert.equal(ontheroad.title(), 'On The Road');
    assert.equal(ontheroad.author.id(), 'jk');
    assert.equal(ontheroad.author.firstName(), 'Jack');
    assert.equal(ontheroad.author.lastName(), 'Kerouac');
    return callback();
  };

  testFind = function(callback) {
    var asimov, howl, ontheroad, whitefang;
    whitefang = book({
      title: 'white fang',
      price: 5
    });
    ontheroad = book({
      title: 'on the road',
      author: 1,
      price: 4
    });
    howl = book({
      title: 'howl',
      author: 2,
      price: 4,
      tax: 50
    });
    asimov = author({
      firstName: 'isaac',
      last_name: 'asimov'
    });
    return functools.map.async(book.save, [whitefang, ontheroad, howl], function(error) {
      if (error) {
        return callback(error);
      }
      return book.find({
        price: 4
      }, function(error, results) {
        assert.equal(results.length, 2);
        assert.equal(results[0].title(), 'On The Road');
        assert.equal(results[0].author(), 1);
        assert.equal(results[0].price(), '$4.8');
        assert.equal(results[0].price.raw(), 4);
        assert.equal(results[0].tax(), 20);
        assert.equal(results[1].title(), 'Howl');
        assert.equal(results[1].author(), 2);
        assert.equal(results[1].price(), '$6');
        assert.equal(results[1].price.raw(), 4);
        assert.equal(results[1].tax(), 50);
        return author.save(asimov, function(error, id) {
          if (error) {
            return callback(error);
          }
          return author.find({
            'id': id
          }, function(error, results) {
            if (error) {
              return callback(error);
            }
            assert.equal(results.length, 1);
            assert.equal(results[0].firstName(), 'Isaac');
            assert.equal(results[0].lastName(), 'Asimov');
            return callback();
          });
        });
      });
    });
  };

  testGet = function(callback) {
    var whitefang;
    whitefang = book({
      title: 'white fang',
      author: 'jl'
    });
    return book.save(whitefang, function(error, id) {
      if (error) {
        return callback(error);
      }
      return book.get(id, function(error, copy) {
        if (error) {
          return callback(error);
        }
        assert.equal(copy.id(), id);
        assert.equal(copy.title(), 'White Fang');
        assert.equal(copy.author(), 'jl');
        return callback();
      });
    });
  };

  testRemove = function(callback) {
    var asimov, whitefang;
    whitefang = book({
      title: 'white fang',
      author: 'jl'
    });
    asimov = author({
      firstName: 'isaac',
      last_name: 'asimov'
    });
    return book.save(whitefang, function(error) {
      var wfid;
      if (error) {
        return callback(error);
      }
      wfid = whitefang.id();
      return author.save(asimov, function(error) {
        var iaid;
        if (error) {
          return callback(error);
        }
        iaid = asimov.id();
        return book.remove(whitefang, function(error) {
          if (error) {
            return callback(error);
          }
          assert.equal(whitefang.id(), void 0);
          return book.get(wfid, function(error, nonexisting) {
            if (error) {
              return callback(error);
            }
            assert.equal(nonexisting, void 0);
            return author.remove(asimov, function(error) {
              if (error) {
                return callback(error);
              }
              assert.equal(asimov.id(), void 0);
              return book.get(iaid, function(error, nonexisting) {
                if (error) {
                  return callback(error);
                }
                assert.equal(nonexisting, void 0);
                return callback();
              });
            });
          });
        });
      });
    });
  };

  testRemoveByQueries = function(callback) {};

  testRemoveSubDocs = function(callback) {};

  testSave = function(callback) {
    var asimov, whitefang;
    whitefang = book({
      title: 'white fang',
      author: 'jl'
    });
    asimov = author({
      firstName: 'isaac',
      last_name: 'asimov'
    });
    return book.save(whitefang, function(error, id) {
      if (error) {
        return callback(error);
      }
      assert.notEqual(id, void 0);
      assert.equal(id, whitefang.id());
      return author.save(asimov, function(error, id) {
        if (error) {
          return callback(error);
        }
        assert.notEqual(id, void 0);
        assert.equal(id, asimov.id());
        return callback();
      });
    });
  };

  testSaveSubDocs = function(callback) {};

  testValidation = function(callback) {};

  testToJSON = function(callback) {
    return callback(new Error('not implemented'));
  };

  module.exports = {
    testCreatingSubDocs: testCreatingSubDocs,
    testFind: testFind,
    testGet: testGet,
    testNewDocument: testNewDocument,
    testSave: testSave,
    testRemove: testRemove,
    testToJSON: testToJSON
  };

}).call(this);
