// Generated by CoffeeScript 1.3.1
(function() {
  var assert, highkick, id, map, testDocument, testId, testSchema;

  highkick = require('highkick');

  assert = require('assert');

  map = require('../lib');

  id = require('../lib/id');

  testSchema = highkick('./schema');

  testDocument = highkick('./document');

  testId = function(callback) {
    var driver1, fields1;
    driver1 = map.newDriver({
      find: function() {},
      get: function() {},
      save: function() {},
      id: 'foo'
    });
    fields1 = {
      foo: String,
      bar: String
    };
    assert.equal(id(driver1), 'foo');
    return callback();
  };

  module.exports = {
    testId: testId,
    testDocument: testDocument,
    testSchema: testSchema
  };

}).call(this);
